### ISSUE TITLE
请问有2020年国赛e题的代码吗，matlab的

### ISSUE THREAD

**Issue by magicsomebody** [personqianduixue/Math_Model#1]

**Comment by personqianduixue** [comment]
可以看看论文附录

**Comment by zmxsen** [comment]
之前有段时间需要帮人获取建模资料，为方便操作将personqianduixue/Math_Model拿到个人库进行下载，如果需要资料可以直接找该库personqianduixue/Math_Model作者。我这个人库将于今晚删除，耽误你的时间，非常抱歉，谢谢。



在 2022-04-12 23:58:01，"qianduixue" ***@***.***> 写道：

Closed #1.
